### ISSUE TITLE
Spring boot starter java.lang.ClassNotFoundException: kotlinx.coroutines.selects.SelectImplementation

### ISSUE THREAD

**Issue by iamsteveholmes** [klogging/klogging#188]
I'm getting the following error while using the Spring Boot Starter:

Exception in thread "DefaultDispatcher-worker-3" java.lang.NoClassDefFoundError: kotlinx/coroutines/selects/SelectImplementation
        at io.klogging.sending.BatchingKt.receiveBatch(Batching.kt:61)
        at io.klogging.internal.Sink$sinkChannel$2$1.invokeSuspend(Sink.kt:58)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(sink-stdout), StandaloneCoroutine{Cancelling}@5b493071, Dispatchers.Default]
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.selects.SelectImplementation
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        
I checked and I'm using the same version of coroutines-core as klogging.  Any thoughts?

**Comment by mjstrasser** [comment]
Hi @iamsteveholmes, thanks for raising this issue. I will have a look as soon as I can.

**Comment by mjstrasser** [comment]
I am able to reproduce the issue in a very simple Spring Boot 3.x application with Klogging.

I will have some more information tomorrow (it is now late at night in eastern Australia).

**Comment by mjstrasser** [comment]
The error occurs in code that uses a [coroutine select expression](https://kotlinlang.org/docs/select-expression.html) to receive log events from sink coroutine channels in batches. That code uses an experimental coroutine API.

`java.lang.NoClassDefFoundError` is thrown, which indicates a class not being loaded when necessary or not being initialised correctly. I cannot tell what is happening here.

Version 0.5.7 of all Klogging (and other artifacts) uses a workaround that receives log events from sink coroutine channels individually, instead of in batches.
