### ISSUE TITLE
JSON parsing error printed to console when HOCON klogging.conf is used

### ISSUE THREAD

**Issue by gavvvr** [klogging/klogging#233]
Hi.
There is a confusing error and stacktrace printed to console when totally valid HOCON configuration file is used.

Given the following `klogging.conf`:

```hocon
sinks {
  stdout {
    renderWith = RENDER_CLEF
    sendTo = STDOUT
  }
}
logging = [
  {
    levelRanges = [
      {
        fromMinLevel = TRACE
        toSinks = [stdout]
      }
    ]
  }
]
```

you will get the following confusing log message on application startup:

<details>
  <summary>Confusing error and stacktrace</summary>

```
08:23:07.385391  WARN [                main] :    JsonConfiguration : Exception parsing JSON
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected start of the object '{', but had 's' instead at path: $
JSON input: sinks {
  stdout {
    renderWith = RENDER_CLEF
    sendTo = STDOUT
  }
}
logging = [
  {
    levelRanges = [
      {
        fromMinLevel = TRACE
        toSinks = [stdout]
      }
    ]
  }
]

	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:596)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json(AbstractJsonLexer.kt:233)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$kotlinx_serialization_json$default(AbstractJsonLexer.kt:228)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.unexpectedToken(AbstractJsonLexer.kt:225)
	at kotlinx.serialization.json.internal.StringJsonLexer.consumeNextToken(StringJsonLexer.kt:74)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:102)
	at io.klogging.config.FileConfiguration$$serializer.deserialize(FileConfiguration.kt:46)
	at io.klogging.config.FileConfiguration$$serializer.deserialize(FileConfiguration.kt:46)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.internal.NullableSerializer.deserialize(NullableSerializer.kt:30)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at io.klogging.config.JsonConfiguration.readConfig$klogging(JsonConfiguration.kt:81)
	at io.klogging.config.JsonConfiguration.configure(JsonConfiguration.kt:57)
	at io.klogging.config.Files_jvmKt.configureFromFile(Files.jvm.kt:77)
	at io.klogging.config.FilesKt$configLoadedFromFile$2.invoke(Files.kt:55)
	at io.klogging.config.FilesKt$configLoadedFromFile$2.invoke(Files.kt:54)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.klogging.config.FilesKt.getConfigLoadedFromFile(Files.kt:54)
	at io.klogging.internal.KloggingEngine$configuration$2.invoke(KloggingEngine.kt:53)
	at io.klogging.internal.KloggingEngine$configuration$2.invoke(KloggingEngine.kt:51)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.klogging.internal.KloggingEngine.getConfiguration$klogging(KloggingEngine.kt:51)
	at io.klogging.NoCoLoggingKt.noCoLoggerFor(NoCoLogging.kt:38)
	at io.klogging.NoCoLoggingKt.noCoLogger(NoCoLogging.kt:47)
	at io.klogging.slf4j.NoCoLoggerFactory.getLogger(NoCoLoggerFactory.kt:36)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:422)
	at org.example.AppKt.<clinit>(App.kt:5)
```
</details>

This does not look good if your HOCON klogging.conf is totally valid.

**Comment by mjstrasser** [comment]
Hi @gavvvr, thanks for bringing this to my attention.

That is indeed an ugly and unhelpful error message. It is generated by the [KotlinX HOCON Serialization](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-hocon/kotlinx.serialization.hocon/-hocon/) library that Klogging uses. 
Unfortunately, this library is experimental (it is annotated with [ExperimentalSerializationApi](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-experimental-serialization-api/index.html) so there are risks using it. 

I am able to reproduce the exception with your configuration file and have seen similar ones in my own projects. Using `=` instead of `:`, and omitting `,` between items both seem to cause these exceptions.

I will see if I can get Klogging to ignore selected exceptions. I will update the documentation to warn users of the issue.

**Comment by mjstrasser** [comment]
I had another look at it. It is using the JSON parser when I don’t think it should.

I will let you know what I find.

**Comment by gavvvr** [comment]
> It is using the JSON parser when I don’t think it should.

Yeah, it fails on attempt to parse it as JSON first, and that's where that ugly exception is produced. Then it falls back to HOCON parser, which behaves as expected and successfully loads the HOCON config.

For reference:
https://github.com/klogging/klogging/blob/e8d8eb4b00c92cf1fa785cb1a7551462bbb5c497/klogging/src/jvmMain/kotlin/io/klogging/config/Files.jvm.kt#L77C5-L77C92

**Comment by mjstrasser** [comment]
I have just discovered that. It seemed like a good idea at the time. 😄 

Fixing it now.

**Comment by mjstrasser** [comment]
Latest snapshot has the fix, that appears to work.

I will test it some more and include it in a release in the next day or so.

**Comment by mjstrasser** [comment]
[Release 0.5.10](https://github.com/klogging/klogging/releases/0.5.10) of Klogging contains the fix to this bug.
